global using AutoMapper;
global using LittleByte.AspNet;
global using LittleByte.Common;
global using Microsoft.AspNetCore.Mvc;
global using NSwag.Annotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Net;
global using Controller = LittleByte.AspNet.Controller;
global using ResponseType = LittleByte.AspNet.ResponseTypeAttribute;
global using Task = Froggie.Domain.Tasks.Task;