name: froggie-core-ci

on:
  push:
    branches: [ "init" ]
  pull_request:
    branches: [ "init" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: env-version
      run: echo "VERSION=1.0.0-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: env-package_name
      run: echo "PACKAGE_NAME=steveyeager.jfrog.io/froggie:ci-$VERSION" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: build
      run: docker build ./Froggie --file ./Froggie/Source/Froggie.Api/Dockerfile -t $PACKAGE_NAME
    - name: docker-login
      run: docker login -u froggie-github steveyeager.jfrog.io -p ${{secrets.ARTIFACTORY_TOKEN}}
    - name: docker-push
      run: docker push $PACKAGE_NAME
